// Drawer
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

// Covid
export const COUNTRIES_FETCHED = "COUNTRIES_FETCHED";
export const COUNTRY_SELECTED = "COUNTRY_SELECTED";
export const CHART_DATA_FETCHED = "CHART_DATA_FETCHED";
export const CASE_TYPE_SET = "CASE_TYPE_SET";
